name: Compile Latex as PDF
# Compiles the latex graphics, then compiles the latex source, then uploads the pdf
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Set up Git repository
        uses: actions/checkout@v4
      # Compile graphics folder LaTeX
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: graphics
          root_file: "*.tex"
          latexmk_shell_escape: true
          extra_system_packages: inkscape      
      # Compile main LaTeX
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      # Upload PDF file as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      # Copy file to deploy folder
      - run: mkdir dist
      - run: cp main.pdf dist/ma2.pdf
      # Upload PDF to server
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rltgoDzvO"
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ vars.REMOTE_TARGET }}  # E.g., "~/public_html/MA2/draft/"
            EXCLUDE: ""






          
